### PR TITLE
Made separate Packages for server and client

### PR DESCRIPTION
**Pull request by AirlineDog**
I also fixed some minor isues

### CODE REVIEW

**Review by Chrysoula7 — COMMENTED** [review]
Will have to make a method in Profile class to "call" it only with URL arguments

**Comment by AirlineDog** [comment]
I made method ` public static void showUrl(String url)` in `Url` class to call from client when you want to show a site.
Nice observation thanks.

**Review by vickyviolintzi — COMMENTED** [review]
The method inputs won't work if the user inserts an int out of bounds.
I also suggest to change in to private.

**Comment by AirlineDog** [comment]
> The method inputs won't work if the user inserts an int out of bounds.
> I also suggest to change in to private.

Done

**Review by ghost — APPROVED** [review]
Ιt seems good to me!

**Review by Botonis — COMMENTED** [review]
it also seems good to me!

**Review by konstasaret — COMMENTED** [review]
Good job friends

**Review by konstasaret — COMMENTED** [review]
I will approve it now!

**Review by konstasaret — APPROVED** [review]
Approved!

**Comment by konstasaret** [comment]
We are all done!

**Review by vickyviolintzi — COMMENTED** [review]
It was nice to cooperate with you guys!

**Comment by konstasaret** [comment]
thank you love

**Pull request merged**
